export const tittle = 'Bienvenidos a mi mundo'
export const subtittle = 'Me complace tenerle como visitante!'
export const one = 'Mi nombre es Macarena Castillo Ruiz y siempre he estado fascinada por la tecnología. Soy una persona curiosa por todo y me encanta aprender. Adoro explorar nuevas formas de hacer las cosas.'
export const two = 'Estoy emocionada de ser parte de la comunidad de programadores y es mi aspiración poder compartir mi pasión con otros. A través de mi trabajo, espero poder contribuir al desarrollo de la tecnología y hacer una diferencia.'
export const three = 'Me considero una persona perseverante y comprometida, siempre dispuesta a enfrentar nuevos desafíos. Disfruto creando soluciones innovadoras y eficientes a través del código.'
export const four = 'Gracias por tomarse el tiempo de leer mi presentación'
export const five = '¡Le saludo muy cordialmente y le deseo un gran día!'